name: Python Check

on:
  push:
  pull_request:

jobs:
  compile:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Compile source
        run: python -m py_compile gpt_auto_gui.pyw
